### ISSUE TITLE
Tracking issue of the missing failing tests from `getCanonicalLocales`

### ISSUE THREAD

**Issue by jedel1043** [jedel1043/icu4x-test262#1]
- [x] https://github.com/tc39/test262/blob/main/test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-calendar.js
- [x] https://github.com/tc39/test262/blob/main/test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-timezone.js
- [x] https://github.com/tc39/test262/blob/main/test/intl402/Intl/getCanonicalLocales/transformed-ext-canonical.js
- [x] https://github.com/tc39/test262/blob/main/test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-col-strength.js
- [x] https://github.com/tc39/test262/blob/main/test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-measurement-system.js
- [x] https://github.com/tc39/test262/blob/main/test/intl402/Intl/getCanonicalLocales/error-cases.js
- [x] https://github.com/tc39/test262/blob/main/test/intl402/Intl/getCanonicalLocales/invalid-tags.js
- [x] https://github.com/tc39/test262/blob/main/test/intl402/Intl/getCanonicalLocales/transformed-ext-valid.js
- [x] https://github.com/tc39/test262/blob/main/test/intl402/Intl/getCanonicalLocales/transformed-ext-invalid.js
- [x] https://github.com/tc39/test262/blob/main/test/intl402/Intl/getCanonicalLocales/non-iana-canon.js
